# Generated by Django 3.0.8 on 2020-07-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComerceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
